name: Build and Publish UI Image

on: 
  push:
    branches:
      - master
    paths:
      - 'days-without-incidents-ui/version.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1  
    - name: build
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: ./build/build-publish-image.sh --project days-without-incidents-ui
